config/routes.rb
Rails.application.routes.draw do
  root      'static_pages#home'
  get       '/help',              to:   'static_pages#help'
  get       '/about',             to:   'static_pages#about'
  get       '/contact',           to:   'static_pages#contact'
  get       '/signup',            to:   'users#new'
  post      '/signup',            to:   'users#create'
  get       '/login',             to:   'sessions#new'
  post      '/login',             to:   'sessions#create'
  delete    '/logout',            to:   'sessions#destroy'
  resources :users do
    member do
      get   :following, :followers
    end
  end
  resources :account_activations, only: :edit
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :talks,               only: [:show, :create] do
    member do
      post  :memberships, :messages
      #post  :memberships,         to:   'memberships#create'
      #post  :messages,            to:   'messages#create'
    end
  end
  resources :memberships,         only: :destroy
  resources :messages,            only: :destroy
end

app/models/talk.rb
class Talk < ApplicationRecord
  has_many :memberships, dependent: :destroy
  has_many :members, class_name: "User", through: :memberships, source: :user
  has_many :messages, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  
  # メンバーのユーザー名を", "で連結した文字列を指定した長さで返す。
  def title(current_user, length=100)
    counter = " (#{members.count})"
    length -= counter.length
    other_members = members.select{ |member| current_user != member }
    title = other_members.collect{ |member| member.name }.join(', ')
    title = title[0...length] + '...' if title.length > length
    if other_members.count > 2
      title + counter
    else
      title
    end
  end
  
  def latest_message
    messages.last if messages.count > 0
  end
  
  # トークから退出する
  def leave(user)
    membership = memberships.find_by(user: user)
    return false if membership.nil?
    !!(membership.destroy)
  end
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  before_action :logged_in_user
  before_action :correct_member, only: [:show, :messages]
  
  def show
    @messages = @talk.messages
    @message = Message.new
  end
  
  def create
    @talk = Talk.new
    @talk.memberships.build(user_id: current_user.id)
    @talk.memberships.build(user_id: params[:member_id])
    @talk.save
    redirect_to @talk
  end
  
  def messages
    @message = Message.new(message_params)
    # トークの更新日時を更新
    @talk.touch
    if @message.save
      redirect_to @talk
    else
      @messages = @talk.messages
      render "show"
    end
  end
  
  private
    
    def message_params
      params[:message].merge!({ user_id: current_user.id, talk_id: @talk.id })
      params.require(:message).permit(:user_id, :talk_id, :content)
    end
    
    def correct_member
      @talk = current_user.talks.find_by(id: params[:id])
      redirect_to root_url if @talk.nil?
    end
    
    def correct_user
      @message = current_user.messages.find_by(id: params[:id])
      redirect_to root_url if @message.nil?
    end
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/views/talks/_talk.html.erb
<li id="talk-<%=talk.id%>">
  <% message = talk.latest_message %>
  <% membership = talk.memberships.find_by(user: current_user) %>
  <%= gravatar_for(message.nil? ? talk.memberships.first.user : message.user, size: 50) %>
  <%= link_to 'leave', membership_path(membership),
                                    class: "delete",
                                    method: :delete,
                                    data: { confirm: "You sure?" } %>
  <%= link_to(talk) do %>
    <span class="title"><%= talk.title(current_user, 50) %></span>
    <span class="content"><%= message.content unless message.nil? %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(talk.updated_at) %> ago.
    </span>
  <% end %>
</li>

app/views/talks/show.html.erb
<% title = @talk.title(current_user, 50) %>
<% provide(:title, title) %>
<h1><%= title %></h1>

<div class="row" >
  <div class="col-md-8 col-md-offset-2">
    <ul class="messages">
      <%= render @messages %>
    </ul>
    
    <%= form_for @message, url: messages_talk_path(@talk),
                          html: { class: 'message-form'} do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="field">
        <%= f.text_area :content, class: "content" %>
      </div>
      <%= f.submit "Send", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>